config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :zikrs
  devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
  root 'zikrs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :zikrs
end

app/models/zikr.rb
class Zikr < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/zikrs_controller.rb
class ZikrsController < ApplicationController
  before_action :set_zikr, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /zikrs
  # GET /zikrs.json
  def index
    @zikrs = Zikr.paginate(:page => params[:page], per_page: 100)
  end

  # GET /zikrs/1
  # GET /zikrs/1.json
  def show
  end

  # GET /zikrs/new
  def new
    @zikr = current_user.zikrs.build
  end

  # GET /zikrs/1/edit
  def edit
  end

  # POST /zikrs
  # POST /zikrs.json
  def create
    @zikr = current_user.zikrs.build(zikr_params)

    respond_to do |format|
      if @zikr.save
        format.html { redirect_to @zikr, notice: 'آپ کی معلومات درج کر لی گئی ہے.' }
        format.json { render :show, status: :created, location: @zikr }
      else
        format.html { render :new }
        format.json { render json: @zikr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zikrs/1
  # PATCH/PUT /zikrs/1.json
  def update
    respond_to do |format|
      if @zikr.update(zikr_params)
        format.html { redirect_to @zikr, notice: 'Zikr was successfully updated.' }
        format.json { render :show, status: :ok, location: @zikr }
      else
        format.html { render :edit }
        format.json { render json: @zikr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zikrs/1
  # DELETE /zikrs/1.json
  def destroy
    @zikr.destroy
    respond_to do |format|
      format.html { redirect_to zikrs_url, notice: 'Zikr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zikr
      @zikr = Zikr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zikr_params
      params.require(:zikr).permit(:name, :city, :country, :phone, :date, :kalma_tayyaba, :durud_sharif, :astagfaar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zikrs_helper.rb
module ZikrsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zkr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= link_to 'Sign Out', destroy_user_session_path %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user && current_user.admin %>
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Sign Out', destroy_user_session_path %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/zikrs/_form.html.erb
<%= form_with(model: zikr, local: true) do |form| %>
  <% if zikr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zikr.errors.count, "error") %> prohibited this zikr from being saved:</h2>

      <ul>
      <% zikr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>
براہ مہربانی اپنی معلومات درج کریں
 </h2>
<div class="table-wrapper">
  <div class="field">
<h2>:آپ کا نام</h2>
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>
</div></br>
----------------------------------------------------
</br>
<div class="table-wrapper">
  <div class="field">
    <h2>آپ کا شہر</h2>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
</div>
</br>
----------------------------------------------------
</br>
<div class="table-wrapper">
  <div class="field">
    <h2>آپ کا ملک</h2>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>
  </div>
</br>
  ----------------------------------------------------
  </br>
  <div class="table-wrapper">
    <div class="field">
      <h2>فون نمبر</h2>
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  </div>
</br>
  ----------------------------------------------------
  </br>
  <div class="table-wrapper">
    <div class="field">
      <h2>آج کی تاریخ</h2>
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>
</div>
</br>
------------------------------------------------------
</br>
  <div class="field">
    <div class="table-wrapper">

        <h2>کلمہ طیبہ  :  لآ اِلَهَ اِلّا اللّهُ مُحَمَّدٌ رَسُوُل اللّهِ</h2>
    <%= form.label :kalma_tayyaba %>
    <%= form.number_field :kalma_tayyaba %>
  </div>
</div>
</br>
-------------------------------------------------------
</br>
  <div class="field">
    <div class="table-wrapper">

        <h2>درود شریفِ</h2>

    <%= form.label :durud_sharif %>
    <%= form.number_field :durud_sharif %>
  </div>
</div>
</br>
-------------------------------------------------------
</br>
  <div class="field">
    <div class="table-wrapper">
      <h2>استغفار  </h2>


    <%= form.label :astagfaar %>
    <%= form.number_field :astagfaar %>
  </div>
</div>
</br>
  <div class="table-wrapper">
  <div class="actions"><h2>معلومات درج کرنے کے لئے کلک کریں</h2>
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/zikrs/edit.html.erb
<h1>Editing Zikr</h1>

<%= render 'form', zikr: @zikr %>

<%= link_to 'Show', @zikr %> |
<%= link_to 'Back', zikrs_path %>

app/views/zikrs/index.html.erb
<p id="notice"><%= notice %></p>




<% if current_user && current_user.admin %>
<h1>Zikrs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Date</th>
      <th>Kalma tayyaba</th>
      <th>Durud sharif</th>
      <th>Astagfaar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zikrs.each do |zikr| %>
      <tr>

        <td><%= zikr.name %></td>
        <td><%= zikr.city %></td>
        <td><%= zikr.country %></td>
        <td><%= zikr.phone %></td>
        <td><%= zikr.date %></td>
        <td><%= zikr.kalma_tayyaba %></td>
        <td><%= zikr.durud_sharif %></td>
        <td><%= zikr.astagfaar %></td>

        <td><%= link_to 'Show', zikr %></td>
        <td><%= link_to 'Edit', edit_zikr_path(zikr) %></td>
        <td><%= link_to 'Destroy', zikr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
<div class="dim">
<div class="wrapme">
<%= will_paginate @posts %>
</div>
</div>
<br>
<div class="table-wrapper">
<h2>
<%= link_to 'معلومات درج کرنے کے لئے کلک کریں', new_zikr_path %>
</h2>
</div>

app/views/zikrs/new.html.erb
<h1>New Zikr</h1>

<%= render 'form', zikr: @zikr %>
<% if current_user && current_user.admin %>
<%= link_to 'Back', zikrs_path %>
<% end %>

app/views/zikrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zikr.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @zikr.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @zikr.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @zikr.phone %>
</p>

<p>
  <strong>Date:</strong>
  <%= @zikr.date %>
</p>

<p>
  <strong>Kalma tayyaba:</strong>
  <%= @zikr.kalma_tayyaba %>
</p>

<p>
  <strong>Durud sharif:</strong>
  <%= @zikr.durud_sharif %>
</p>

<p>
  <strong>Astagfaar:</strong>
  <%= @zikr.astagfaar %>
</p>
<% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_zikr_path(@zikr) %> |
<%= link_to 'Back', zikrs_path %>
<% end %>
<%= link_to 'SIGN OUT ', destroy_user_session_path %>